
2024-02-20 14:46:18,455 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x73b56faad940>" was accessed, it will be removed in a future version

2024-02-20 14:46:21,853 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2024-02-20 14:50:42,263 - kivy - WARNING - stderr: Process Process-1:

2024-02-20 14:50:42,265 - kivy - WARNING - stderr: Traceback (most recent call last):

2024-02-20 14:50:42,265 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main

2024-02-20 14:50:42,267 - kivy - WARNING - stderr: Traceback (most recent call last):

2024-02-20 14:50:42,268 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap

2024-02-20 14:50:42,268 - kivy - WARNING - stderr:     self.run()

2024-02-20 14:50:42,268 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run

2024-02-20 14:50:42,268 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2024-02-20 14:50:42,269 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/subs/driver/internal_bus.py", line 409, in start

2024-02-20 14:50:42,269 - kivy - WARNING - stderr:     self._setup_interrupts()

2024-02-20 14:50:42,269 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/subs/driver/internal_bus.py", line 403, in _setup_interrupts

2024-02-20 14:50:42,269 - kivy - WARNING - stderr:     self._scheduler.run()

2024-02-20 14:50:42,269 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/sched.py", line 134, in run

2024-02-20 14:50:42,269 - kivy - WARNING - stderr:     while True:

2024-02-20 14:50:42,269 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/sched.py", line 134, in run

2024-02-20 14:50:42,269 - kivy - WARNING - stderr:     while True:

2024-02-20 14:50:42,270 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 1600, in _pydevd_bundle.pydevd_cython.trace_dispatch

2024-02-20 14:50:42,270 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 1457, in _pydevd_bundle.pydevd_cython.SafeCallWrapper.__call__

2024-02-20 14:50:42,270 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 1834, in _pydevd_bundle.pydevd_cython.ThreadTracer.__call__

2024-02-20 14:50:42,270 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 1152, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch

2024-02-20 14:50:42,270 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 1135, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch

2024-02-20 14:50:42,270 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 312, in _pydevd_bundle.pydevd_cython.PyDBFrame.do_wait_suspend

2024-02-20 14:50:42,270 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2024-02-20 14:50:42,270 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2024-02-20 14:50:42,270 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 14:50:42,271 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2024-02-20 14:50:42,271 - kivy - WARNING - stderr:     time.sleep(0.01)

2024-02-20 14:50:42,271 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2024-02-20 14:50:42,271 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2024-02-20 14:50:42,271 - kivy - WARNING - stderr: KeyboardInterrupt

2024-02-20 14:50:42,274 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 88, in _run_code

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:     exec(code, run_globals)

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:     cli.main()

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:     run()

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:     runpy.run_path(target, run_name="__main__")

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:     return _run_module_code(code, init_globals, run_name,

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:     _run_code(code, mod_globals, init_globals,

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:     exec(code, run_globals)

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/main.py", line 322, in <module>

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:     asyncio.run(mainCoro())

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run

2024-02-20 14:50:42,275 - kivy - WARNING - stderr:     return runner.run(main)

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:     return self._loop.run_until_complete(task)

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:     self.run_forever()

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:     self._run_once()

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:     handle._run()

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:     self._context.run(self._callback, *self._args)

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/subs/driver/interface_factory.py", line 211, in init_interface

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:     self.connected_internal_devices[interface.device] = interface

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:                                                         ^^^^^^^^^

2024-02-20 14:50:42,276 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/subs/driver/interface_factory.py", line 211, in init_interface

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:     self.connected_internal_devices[interface.device] = interface

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:                                                         ^^^^^^^^^

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 1457, in _pydevd_bundle.pydevd_cython.SafeCallWrapper.__call__

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 701, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 1152, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 1135, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 312, in _pydevd_bundle.pydevd_cython.PyDBFrame.do_wait_suspend

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:     time.sleep(0.01)

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2024-02-20 14:50:42,277 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2024-02-20 14:50:42,277 - kivy - WARNING - stderr: KeyboardInterrupt

2024-02-20 14:50:42,452 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>

2024-02-20 14:50:42,452 - kivy - WARNING - stderr: Traceback (most recent call last):

2024-02-20 14:50:42,452 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1583, in _shutdown

2024-02-20 14:50:42,453 - kivy - WARNING - stderr:     lock.acquire()

2024-02-20 14:50:42,453 - kivy - WARNING - stderr: KeyboardInterrupt: 

2024-02-20 14:54:57,053 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x73d42c46bf50>" was accessed, it will be removed in a future version

2024-02-20 14:55:00,437 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2024-02-20 15:08:44,415 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7995bbac7f50>" was accessed, it will be removed in a future version

2024-02-20 15:08:47,768 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2024-02-20 16:16:48,514 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x79a415d6fe70>" was accessed, it will be removed in a future version

2024-02-20 16:16:51,901 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2024-02-20 16:26:38,710 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x79e0479e7ee0>" was accessed, it will be removed in a future version

2024-02-20 16:26:42,073 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2024-02-20 16:29:54,114 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x708944103e70>" was accessed, it will be removed in a future version

2024-02-20 16:29:57,480 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2024-02-20 16:31:10,062 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7aac83417e70>" was accessed, it will be removed in a future version

2024-02-20 16:31:13,456 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2024-02-20 16:36:28,975 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x75b49e363f50>" was accessed, it will be removed in a future version

2024-02-20 16:36:32,359 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2024-02-20 16:37:27,671 - kivy - WARNING - stderr: Process Process-1:

2024-02-20 16:37:27,673 - kivy - WARNING - stderr: Traceback (most recent call last):

2024-02-20 16:37:27,673 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap

2024-02-20 16:37:27,673 - kivy - WARNING - stderr:     self.run()

2024-02-20 16:37:27,674 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run

2024-02-20 16:37:27,674 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2024-02-20 16:37:27,674 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/subs/driver/internal_bus.py", line 408, in start

2024-02-20 16:37:27,674 - kivy - WARNING - stderr:     self._setup_interrupts()

2024-02-20 16:37:27,674 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/subs/driver/internal_bus.py", line 402, in _setup_interrupts

2024-02-20 16:37:27,674 - kivy - WARNING - stderr:     self._scheduler.run()

2024-02-20 16:37:27,674 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/sched.py", line 149, in run

2024-02-20 16:37:27,674 - kivy - WARNING - stderr:     delayfunc(time - now)

2024-02-20 16:37:27,674 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2024-02-20 16:37:27,674 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2024-02-20 16:37:27,675 - kivy - WARNING - stderr: KeyboardInterrupt

2024-02-20 16:37:27,816 - kivy - WARNING - stderr: Traceback (most recent call last):

2024-02-20 16:37:27,816 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run

2024-02-20 16:37:27,816 - kivy - WARNING - stderr:     return runner.run(main)

2024-02-20 16:37:27,816 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^

2024-02-20 16:37:27,816 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run

2024-02-20 16:37:27,816 - kivy - WARNING - stderr:     return self._loop.run_until_complete(task)

2024-02-20 16:37:27,816 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 16:37:27,816 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2024-02-20 16:37:27,817 - kivy - WARNING - stderr:     self.run_forever()

2024-02-20 16:37:27,817 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2024-02-20 16:37:27,817 - kivy - WARNING - stderr:     self._run_once()

2024-02-20 16:37:27,817 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once

2024-02-20 16:37:27,817 - kivy - WARNING - stderr:     handle._run()

2024-02-20 16:37:27,817 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run

2024-02-20 16:37:27,817 - kivy - WARNING - stderr:     self._context.run(self._callback, *self._args)

2024-02-20 16:37:27,818 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/subs/driver/interface_drivers/controller_template.py", line 56, in on_connect_default

2024-02-20 16:37:27,818 - kivy - WARNING - stderr:     return await self.on_connect(*args, **kwargs)

2024-02-20 16:37:27,818 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 16:37:27,818 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/subs/driver/interfaces.py", line 233, in _on_connect

2024-02-20 16:37:27,818 - kivy - WARNING - stderr:     self.on_connect(self)

2024-02-20 16:37:27,818 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/subs/driver/interface_factory.py", line 247, in on_connect

2024-02-20 16:37:27,818 - kivy - WARNING - stderr:     self.external_on_connect(interface)

2024-02-20 16:37:27,818 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/subs/input_ouput.py", line 541, in connect_interface

2024-02-20 16:37:27,818 - kivy - WARNING - stderr:     self.interfaces[interface.ID] = interface

2024-02-20 16:37:27,818 - kivy - WARNING - stderr:     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^

2024-02-20 16:37:27,818 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 974, in kivy.properties.ObservableDict.__setitem__

2024-02-20 16:37:27,819 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 944, in kivy.properties.observable_dict_dispatch

2024-02-20 16:37:27,819 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 625, in kivy.properties.Property.dispatch

2024-02-20 16:37:27,819 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 606, in kivy.properties.Property._dispatch

2024-02-20 16:37:27,819 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch

2024-02-20 16:37:27,819 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1189, in kivy._event.EventObservers._dispatch

2024-02-20 16:37:27,819 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/lang/builder.py", line 72, in call_fn

2024-02-20 16:37:27,819 - kivy - WARNING - stderr:     setattr(element, key, e_value)

2024-02-20 16:37:27,819 - kivy - WARNING - stderr:   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__

2024-02-20 16:37:27,820 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__

2024-02-20 16:37:27,820 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 939, in kivy.properties.ListProperty.set

2024-02-20 16:37:27,820 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 567, in kivy.properties.Property.set

2024-02-20 16:37:27,820 - kivy - WARNING - stderr:   File "kivy/properties.pyx", line 606, in kivy.properties.Property._dispatch

2024-02-20 16:37:27,820 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch

2024-02-20 16:37:27,820 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1189, in kivy._event.EventObservers._dispatch

2024-02-20 16:37:27,820 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/lang/builder.py", line 60, in custom_callback

2024-02-20 16:37:27,820 - kivy - WARNING - stderr:     exec(__kvlang__.co_value, idmap)

2024-02-20 16:37:27,820 - kivy - WARNING - stderr:   File "<string>", line 50, in <module>

2024-02-20 16:37:27,820 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/subs/gui/screens/rec.py", line 424, in interface_disconnect

2024-02-20 16:37:27,821 - kivy - WARNING - stderr:     print('disconnect ITNTERFACEE' * 100)

2024-02-20 16:37:27,821 - kivy - WARNING - stderr:        ^^^^^^^^^

2024-02-20 16:37:27,821 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/20231109/MooseWare/rec_app/subs/gui/screens/rec.py", line 424, in interface_disconnect

2024-02-20 16:37:27,821 - kivy - WARNING - stderr:     print('disconnect ITNTERFACEE' * 100)

2024-02-20 16:37:27,821 - kivy - WARNING - stderr:        ^^^^^^^^^

2024-02-20 16:37:27,821 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 1457, in _pydevd_bundle.pydevd_cython.SafeCallWrapper.__call__

2024-02-20 16:37:27,821 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 701, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch

2024-02-20 16:37:27,821 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 1395, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch

2024-02-20 16:37:27,821 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 1344, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch

2024-02-20 16:37:27,822 - kivy - WARNING - stderr:   File "_pydevd_bundle/pydevd_cython.pyx", line 312, in _pydevd_bundle.pydevd_cython.PyDBFrame.do_wait_suspend

2024-02-20 16:37:27,822 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2024-02-20 16:37:27,831 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2024-02-20 16:37:27,832 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 16:37:27,832 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2024-02-20 16:37:27,832 - kivy - WARNING - stderr:     time.sleep(0.01)

2024-02-20 16:37:27,832 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2024-02-20 16:37:27,832 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2024-02-20 16:37:27,832 - kivy - WARNING - stderr: KeyboardInterrupt

2024-02-20 16:37:27,832 - kivy - WARNING - stderr: 

2024-02-20 16:37:27,832 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2024-02-20 16:37:27,832 - kivy - WARNING - stderr: 

2024-02-20 16:37:27,832 - kivy - WARNING - stderr: Traceback (most recent call last):

2024-02-20 16:37:27,832 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main

2024-02-20 16:37:27,832 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2024-02-20 16:37:27,833 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 16:37:27,833 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 88, in _run_code

2024-02-20 16:37:27,833 - kivy - WARNING - stderr:     exec(code, run_globals)

2024-02-20 16:37:27,833 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>

2024-02-20 16:37:27,833 - kivy - WARNING - stderr:     cli.main()

2024-02-20 16:37:27,833 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main

2024-02-20 16:37:27,833 - kivy - WARNING - stderr:     run()

2024-02-20 16:37:27,833 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file

2024-02-20 16:37:27,833 - kivy - WARNING - stderr:     runpy.run_path(target, run_name="__main__")

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:     return _run_module_code(code, init_globals, run_name,

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:     _run_code(code, mod_globals, init_globals,

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:     exec(code, run_globals)

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:   File "rec_app/main.py", line 322, in <module>

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:     asyncio.run(mainCoro())

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 187, in run

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:     with Runner(debug=debug) as runner:

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 63, in __exit__

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:     self.close()

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 73, in close

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:     loop.run_until_complete(loop.shutdown_default_executor())

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2024-02-20 16:37:27,834 - kivy - WARNING - stderr:     self.run_forever()

2024-02-20 16:37:27,835 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2024-02-20 16:37:27,835 - kivy - WARNING - stderr:     self._run_once()

2024-02-20 16:37:27,835 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1873, in _run_once

2024-02-20 16:37:27,835 - kivy - WARNING - stderr:     event_list = self._selector.select(timeout)

2024-02-20 16:37:27,835 - kivy - WARNING - stderr:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 16:37:27,835 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/selectors.py", line 468, in select

2024-02-20 16:37:27,835 - kivy - WARNING - stderr:     fd_event_list = self._selector.poll(timeout, max_ev)

2024-02-20 16:37:27,835 - kivy - WARNING - stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 16:37:27,835 - kivy - WARNING - stderr: KeyboardInterrupt

2024-02-20 16:37:29,081 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>

2024-02-20 16:37:29,082 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>Exception in thread Thread-6 (_do_shutdown):

2024-02-20 16:37:29,082 - kivy - WARNING - stderr: Traceback (most recent call last):

2024-02-20 16:37:29,083 - kivy - WARNING - stderr: Traceback (most recent call last):

2024-02-20 16:37:29,084 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1553, in _shutdown

2024-02-20 16:37:29,085 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 580, in _do_shutdown

2024-02-20 16:37:29,085 - kivy - WARNING - stderr:     atexit_call()

2024-02-20 16:37:29,086 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_result, None)

2024-02-20 16:37:29,086 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit

2024-02-20 16:37:29,087 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2024-02-20 16:37:29,088 - kivy - WARNING - stderr:     self._check_closed()

2024-02-20 16:37:29,088 - kivy - WARNING - stderr:     self._check_closed()    t.join()

2024-02-20 16:37:29,089 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2024-02-20 16:37:29,089 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1112, in join

2024-02-20 16:37:29,090 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2024-02-20 16:37:29,091 - kivy - WARNING - stderr:     self._wait_for_tstate_lock()

2024-02-20 16:37:29,091 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2024-02-20 16:37:29,091 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock

2024-02-20 16:37:29,092 - kivy - WARNING - stderr: 

2024-02-20 16:37:29,092 - kivy - WARNING - stderr:     if lock.acquire(block, timeout):

2024-02-20 16:37:29,092 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2024-02-20 16:37:29,093 - kivy - WARNING - stderr:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-02-20 16:37:29,093 - kivy - WARNING - stderr: 

2024-02-20 16:37:29,093 - kivy - WARNING - stderr: Traceback (most recent call last):

2024-02-20 16:37:29,093 - kivy - WARNING - stderr: KeyboardInterrupt: 

2024-02-20 16:37:29,093 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner

2024-02-20 16:37:29,094 - kivy - WARNING - stderr:     self.run()

2024-02-20 16:37:29,095 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 975, in run

2024-02-20 16:37:29,096 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2024-02-20 16:37:29,097 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 582, in _do_shutdown

2024-02-20 16:37:29,098 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_exception, ex)

2024-02-20 16:37:29,099 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2024-02-20 16:37:29,099 - kivy - WARNING - stderr:     self._check_closed()

2024-02-20 16:37:29,100 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2024-02-20 16:37:29,100 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2024-02-20 16:37:29,100 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2024-02-20 16:37:29,271 - kivy - WARNING - stderr: Traceback (most recent call last):

2024-02-20 16:37:29,272 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py", line 2299, in __wait_for_threads_to_finish

2024-02-20 16:37:29,272 - kivy - WARNING - stderr:     time.sleep(1 / 10.)

2024-02-20 16:37:29,272 - kivy - WARNING - stderr: KeyboardInterrupt

2024-02-20 16:38:07,744 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7823c0997e70>" was accessed, it will be removed in a future version

2024-02-20 16:38:11,101 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2024-02-27 11:56:22,961 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x761c77f17ee0>" was accessed, it will be removed in a future version

2024-02-27 11:56:26,655 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2024-02-27 11:56:43,998 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2024-02-27 11:56:43,999 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2024-02-27 11:56:44,004 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2024-02-27 11:56:44,004 - kivy - WARNING - Factory: Ignored class "SetTimeIn" re-declaration. Current -  module: None, cls: None, baseclass: TIn, filename: None. Ignored -  module: None, cls: None, baseclass: TIn, filename: None.

2024-02-27 11:56:44,004 - kivy - WARNING - Factory: Ignored class "SetIntMethod" re-declaration. Current -  module: None, cls: None, baseclass: DROPB, filename: None. Ignored -  module: None, cls: None, baseclass: DROPB, filename: None.

2024-02-27 11:56:44,004 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2024-02-27 11:57:59,395 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2024-02-27 11:57:59,396 - kivy - WARNING - Factory: Ignored class "SetTimeIn" re-declaration. Current -  module: None, cls: None, baseclass: TIn, filename: None. Ignored -  module: None, cls: None, baseclass: TIn, filename: None.

2024-02-27 11:57:59,396 - kivy - WARNING - Factory: Ignored class "SetIntMethod" re-declaration. Current -  module: None, cls: None, baseclass: DROPB, filename: None. Ignored -  module: None, cls: None, baseclass: DROPB, filename: None.

2024-02-27 11:57:59,397 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2024-02-27 11:57:59,403 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2024-02-27 11:57:59,404 - kivy - WARNING - Factory: Ignored class "SetTimeIn" re-declaration. Current -  module: None, cls: None, baseclass: TIn, filename: None. Ignored -  module: None, cls: None, baseclass: TIn, filename: None.

2024-02-27 11:57:59,404 - kivy - WARNING - Factory: Ignored class "SetIntMethod" re-declaration. Current -  module: None, cls: None, baseclass: DROPB, filename: None. Ignored -  module: None, cls: None, baseclass: DROPB, filename: None.

2024-02-27 11:57:59,404 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2024-02-27 11:58:08,660 - kivy - WARNING - INTERFACE: Cannot unpack sample rate: {256.0 Hz

2024-02-27 11:58:35,159 - kivy - WARNING - INTERFACE: Cannot unpack sample rate: {256.0 Hz

2024-02-27 12:00:54,899 - kivy - WARNING - INTERFACE: Cannot unpack sample rate: {"idle":true,"GPIO":{"name":"GPIO Interface","control_str":"[{\"title\": \"GPIO Output\",\"type\": \"stim\",\"desc\": \"Create / Start / Stop gpio output protocol\",\"live_widget\": true,\"key\": \"output\"}]","#ST":0,"record":true,"parameter_names":["GPIO2.0 Hz
