
2023-11-07 15:28:50,124 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f3fe971a0b0>" was accessed, it will be removed in a future version

2023-11-07 15:28:50,922 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2023-11-07 15:28:50,923 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2023-11-07 15:28:53,521 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-07 15:29:25,389 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:29:25,390 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 430, in _handle_exception

2023-11-07 15:29:25,390 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg, exception_type=exception_type)

2023-11-07 15:29:25,390 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-07 15:29:25,390 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-07 15:29:25,390 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-07 15:29:25,390 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-07 15:29:25,390 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,390 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-07 15:29:25,390 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-07 15:29:25,390 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:29:25,390 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:29:25,390 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:29:25,533 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:29:25,533 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 430, in _handle_exception

2023-11-07 15:29:25,533 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg, exception_type=exception_type)

2023-11-07 15:29:25,533 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-07 15:29:25,533 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-07 15:29:25,534 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-07 15:29:25,534 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-07 15:29:25,534 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,534 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-07 15:29:25,534 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-07 15:29:25,534 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:29:25,534 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:29:25,534 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:29:25,535 - kivy - WARNING - stderr: Process Process-1:

2023-11-07 15:29:25,536 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:29:25,537 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap

2023-11-07 15:29:25,537 - kivy - WARNING - stderr:     self.run()

2023-11-07 15:29:25,537 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run

2023-11-07 15:29:25,537 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-07 15:29:25,537 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 406, in start

2023-11-07 15:29:25,537 - kivy - WARNING - stderr:     self._setup_interrupts()

2023-11-07 15:29:25,537 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 400, in _setup_interrupts

2023-11-07 15:29:25,537 - kivy - WARNING - stderr:     self._scheduler.run()

2023-11-07 15:29:25,538 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/sched.py", line 149, in run

2023-11-07 15:29:25,538 - kivy - WARNING - stderr:     delayfunc(time - now)

2023-11-07 15:29:25,538 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:29:25,538 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:29:25,538 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:29:25,675 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:29:25,675 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run

2023-11-07 15:29:25,675 - kivy - WARNING - stderr:     return runner.run(main)

2023-11-07 15:29:25,675 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,675 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run

2023-11-07 15:29:25,675 - kivy - WARNING - stderr:     return self._loop.run_until_complete(task)

2023-11-07 15:29:25,675 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,675 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-07 15:29:25,675 - kivy - WARNING - stderr:     self.run_forever()

2023-11-07 15:29:25,675 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:     self._run_once()

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:     handle._run()

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:     self._context.run(self._callback, *self._args)

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 320, in mainCoro

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:     await app.async_run()

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/app.py", line 968, in async_run

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:     await async_runTouchApp(async_lib=async_lib)

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 597, in async_runTouchApp

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:     await EventLoop.async_mainloop()

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 354, in async_mainloop

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:     await self.async_idle()

2023-11-07 15:29:25,676 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 422, in async_idle

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:     self.dispatch_input()

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 334, in dispatch_input

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:     post_dispatch_input(*pop(0))

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 302, in post_dispatch_input

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:     wid.dispatch('on_touch_up', me)

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:     self.dispatch('on_release')

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1191, in kivy._event.EventObservers._dispatch

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/lang/builder.py", line 55, in custom_callback

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:     exec(__kvlang__.co_value, idmap)

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:   File "<string>", line 42, in <module>

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 217, in open_settings

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:     return super().open_settings(*args)

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,677 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/app.py", line 1084, in open_settings

2023-11-07 15:29:25,678 - kivy - WARNING - stderr:     self._app_settings = self.create_settings()

2023-11-07 15:29:25,678 - kivy - WARNING - stderr:                          ^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,678 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 204, in trace_dispatch

2023-11-07 15:29:25,686 - kivy - WARNING - stderr:     return thread_trace_func(frame, event, arg)

2023-11-07 15:29:25,687 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,687 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 440, in __call__

2023-11-07 15:29:25,687 - kivy - WARNING - stderr:     ).trace_dispatch(frame, event, arg)

2023-11-07 15:29:25,687 - kivy - WARNING - stderr:       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,687 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 988, in trace_dispatch

2023-11-07 15:29:25,687 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg)

2023-11-07 15:29:25,687 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-07 15:29:25,687 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-07 15:29:25,687 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-07 15:29:25,687 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-07 15:29:25,688 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,688 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-07 15:29:25,688 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-07 15:29:25,688 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:29:25,688 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:29:25,688 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:29:25,688 - kivy - WARNING - stderr: 

2023-11-07 15:29:25,688 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-07 15:29:25,688 - kivy - WARNING - stderr: 

2023-11-07 15:29:25,688 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:29:25,688 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main

2023-11-07 15:29:25,688 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-07 15:29:25,688 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,688 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 88, in _run_code

2023-11-07 15:29:25,689 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-07 15:29:25,689 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>

2023-11-07 15:29:25,689 - kivy - WARNING - stderr:     cli.main()

2023-11-07 15:29:25,689 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main

2023-11-07 15:29:25,689 - kivy - WARNING - stderr:     run()

2023-11-07 15:29:25,689 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module

2023-11-07 15:29:25,689 - kivy - WARNING - stderr:     run_module_as_main(options.target, alter_argv=True)

2023-11-07 15:29:25,689 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 322, in <module>

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:     asyncio.run(mainCoro())

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 187, in run

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:     with Runner(debug=debug) as runner:

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 63, in __exit__

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:     self.close()

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 73, in close

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:     loop.run_until_complete(loop.shutdown_default_executor())

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:     self.run_forever()

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:     self._run_once()

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1873, in _run_once

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:     event_list = self._selector.select(timeout)

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,690 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/selectors.py", line 468, in select

2023-11-07 15:29:25,691 - kivy - WARNING - stderr:     fd_event_list = self._selector.poll(timeout, max_ev)

2023-11-07 15:29:25,691 - kivy - WARNING - stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,691 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:29:25,838 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>

2023-11-07 15:29:25,838 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>Exception in thread Thread-7 (_do_shutdown):

2023-11-07 15:29:25,838 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:29:25,838 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1553, in _shutdown

2023-11-07 15:29:25,838 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:29:25,839 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 580, in _do_shutdown

2023-11-07 15:29:25,839 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_result, None)

2023-11-07 15:29:25,839 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_result, None)    atexit_call()

2023-11-07 15:29:25,839 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit

2023-11-07 15:29:25,839 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-07 15:29:25,840 - kivy - WARNING - stderr:     t.join()

2023-11-07 15:29:25,840 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1112, in join

2023-11-07 15:29:25,840 - kivy - WARNING - stderr:     self._wait_for_tstate_lock()

2023-11-07 15:29:25,840 - kivy - WARNING - stderr:     self._wait_for_tstate_lock()    self._check_closed()

2023-11-07 15:29:25,841 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-07 15:29:25,841 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock

2023-11-07 15:29:25,841 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-07 15:29:25,841 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-07 15:29:25,841 - kivy - WARNING - stderr: 

2023-11-07 15:29:25,841 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-07 15:29:25,841 - kivy - WARNING - stderr: 

2023-11-07 15:29:25,842 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:29:25,842 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner

2023-11-07 15:29:25,842 - kivy - WARNING - stderr:     if lock.acquire(block, timeout):

2023-11-07 15:29:25,842 - kivy - WARNING - stderr:     if lock.acquire(block, timeout):    self.run()

2023-11-07 15:29:25,842 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 975, in run

2023-11-07 15:29:25,842 - kivy - WARNING - stderr:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:29:25,842 - kivy - WARNING - stderr: KeyboardInterrupt: 

2023-11-07 15:29:25,843 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-07 15:29:25,844 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 582, in _do_shutdown

2023-11-07 15:29:25,844 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_exception, ex)

2023-11-07 15:29:25,844 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-07 15:29:25,844 - kivy - WARNING - stderr:     self._check_closed()

2023-11-07 15:29:25,845 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-07 15:29:25,845 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-07 15:29:25,845 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-07 15:29:26,283 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:29:26,283 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2299, in __wait_for_threads_to_finish

2023-11-07 15:29:26,283 - kivy - WARNING - stderr:     time.sleep(1 / 10.)

2023-11-07 15:29:26,283 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:29:41,927 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7fe1a0d6a190>" was accessed, it will be removed in a future version

2023-11-07 15:29:42,625 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2023-11-07 15:29:42,625 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2023-11-07 15:29:45,324 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-07 15:30:45,843 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7fa7cfc76120>" was accessed, it will be removed in a future version

2023-11-07 15:30:49,197 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-07 15:31:03,101 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f2650cea120>" was accessed, it will be removed in a future version

2023-11-07 15:31:04,415 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2023-11-07 15:31:04,416 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2023-11-07 15:31:06,474 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-07 15:31:55,990 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:31:55,991 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 430, in _handle_exception

2023-11-07 15:31:55,991 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg, exception_type=exception_type)

2023-11-07 15:31:55,991 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-07 15:31:55,991 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-07 15:31:55,991 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-07 15:31:55,991 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-07 15:31:55,991 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:31:55,991 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-07 15:31:55,991 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-07 15:31:55,991 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:31:55,991 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:31:55,991 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:31:56,138 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:31:56,139 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 430, in _handle_exception

2023-11-07 15:31:56,139 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg, exception_type=exception_type)

2023-11-07 15:31:56,139 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-07 15:31:56,139 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-07 15:31:56,140 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-07 15:31:56,140 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-07 15:31:56,140 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:31:56,140 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-07 15:31:56,140 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-07 15:31:56,140 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:31:56,140 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:31:56,140 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:31:56,142 - kivy - WARNING - stderr: Process Process-1:

2023-11-07 15:31:56,144 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:31:56,147 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap

2023-11-07 15:31:56,148 - kivy - WARNING - stderr:     self.run()

2023-11-07 15:31:56,149 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run

2023-11-07 15:31:56,149 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-07 15:31:56,150 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 406, in start

2023-11-07 15:31:56,150 - kivy - WARNING - stderr:     self._setup_interrupts()

2023-11-07 15:31:56,151 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 400, in _setup_interrupts

2023-11-07 15:31:56,151 - kivy - WARNING - stderr:     self._scheduler.run()

2023-11-07 15:31:56,151 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/sched.py", line 149, in run

2023-11-07 15:31:56,151 - kivy - WARNING - stderr:     delayfunc(time - now)

2023-11-07 15:31:56,152 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:31:56,152 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:31:56,152 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:31:56,284 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:31:56,284 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run

2023-11-07 15:31:56,284 - kivy - WARNING - stderr:     return runner.run(main)

2023-11-07 15:31:56,284 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^

2023-11-07 15:31:56,285 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run

2023-11-07 15:31:56,285 - kivy - WARNING - stderr:     return self._loop.run_until_complete(task)

2023-11-07 15:31:56,285 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:31:56,285 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-07 15:31:56,285 - kivy - WARNING - stderr:     self.run_forever()

2023-11-07 15:31:56,285 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-07 15:31:56,285 - kivy - WARNING - stderr:     self._run_once()

2023-11-07 15:31:56,286 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once

2023-11-07 15:31:56,286 - kivy - WARNING - stderr:     handle._run()

2023-11-07 15:31:56,286 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run

2023-11-07 15:31:56,286 - kivy - WARNING - stderr:     self._context.run(self._callback, *self._args)

2023-11-07 15:31:56,286 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 320, in mainCoro

2023-11-07 15:31:56,286 - kivy - WARNING - stderr:     await app.async_run()

2023-11-07 15:31:56,287 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/app.py", line 968, in async_run

2023-11-07 15:31:56,287 - kivy - WARNING - stderr:     await async_runTouchApp(async_lib=async_lib)

2023-11-07 15:31:56,287 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 597, in async_runTouchApp

2023-11-07 15:31:56,287 - kivy - WARNING - stderr:     await EventLoop.async_mainloop()

2023-11-07 15:31:56,287 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 354, in async_mainloop

2023-11-07 15:31:56,287 - kivy - WARNING - stderr:     await self.async_idle()

2023-11-07 15:31:56,288 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 422, in async_idle

2023-11-07 15:31:56,288 - kivy - WARNING - stderr:     self.dispatch_input()

2023-11-07 15:31:56,288 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 334, in dispatch_input

2023-11-07 15:31:56,288 - kivy - WARNING - stderr:     post_dispatch_input(*pop(0))

2023-11-07 15:31:56,288 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 302, in post_dispatch_input

2023-11-07 15:31:56,288 - kivy - WARNING - stderr:     wid.dispatch('on_touch_up', me)

2023-11-07 15:31:56,288 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch

2023-11-07 15:31:56,288 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up

2023-11-07 15:31:56,289 - kivy - WARNING - stderr:     self.dispatch('on_release')

2023-11-07 15:31:56,289 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch

2023-11-07 15:31:56,289 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch

2023-11-07 15:31:56,289 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1191, in kivy._event.EventObservers._dispatch

2023-11-07 15:31:56,289 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/lang/builder.py", line 55, in custom_callback

2023-11-07 15:31:56,289 - kivy - WARNING - stderr:     exec(__kvlang__.co_value, idmap)

2023-11-07 15:31:56,290 - kivy - WARNING - stderr:   File "<string>", line 42, in <module>

2023-11-07 15:31:56,290 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 217, in open_settings

2023-11-07 15:31:56,290 - kivy - WARNING - stderr:     return super().open_settings(*args)

2023-11-07 15:31:56,290 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:31:56,290 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/app.py", line 1084, in open_settings

2023-11-07 15:31:56,291 - kivy - WARNING - stderr:     self._app_settings = self.create_settings()

2023-11-07 15:31:56,291 - kivy - WARNING - stderr:                          ^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:31:56,291 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 204, in trace_dispatch

2023-11-07 15:31:56,300 - kivy - WARNING - stderr:     return thread_trace_func(frame, event, arg)

2023-11-07 15:31:56,300 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:31:56,300 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 440, in __call__

2023-11-07 15:31:56,301 - kivy - WARNING - stderr:     ).trace_dispatch(frame, event, arg)

2023-11-07 15:31:56,301 - kivy - WARNING - stderr:       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:31:56,301 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 988, in trace_dispatch

2023-11-07 15:31:56,301 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg)

2023-11-07 15:31:56,301 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-07 15:31:56,301 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-07 15:31:56,301 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-07 15:31:56,302 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-07 15:31:56,302 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:31:56,302 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-07 15:31:56,302 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-07 15:31:56,302 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:31:56,302 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:31:56,302 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:31:56,302 - kivy - WARNING - stderr: 

2023-11-07 15:31:56,302 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-07 15:31:56,302 - kivy - WARNING - stderr: 

2023-11-07 15:31:56,303 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:31:56,303 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main

2023-11-07 15:31:56,303 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-07 15:31:56,303 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:31:56,303 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 88, in _run_code

2023-11-07 15:31:56,303 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-07 15:31:56,303 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>

2023-11-07 15:31:56,303 - kivy - WARNING - stderr:     cli.main()

2023-11-07 15:31:56,303 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main

2023-11-07 15:31:56,303 - kivy - WARNING - stderr:     run()

2023-11-07 15:31:56,303 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module

2023-11-07 15:31:56,303 - kivy - WARNING - stderr:     run_module_as_main(options.target, alter_argv=True)

2023-11-07 15:31:56,303 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 322, in <module>

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:     asyncio.run(mainCoro())

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 187, in run

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:     with Runner(debug=debug) as runner:

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 63, in __exit__

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:     self.close()

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 73, in close

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:     loop.run_until_complete(loop.shutdown_default_executor())

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:     self.run_forever()

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:     self._run_once()

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1873, in _run_once

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:     event_list = self._selector.select(timeout)

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:31:56,304 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/selectors.py", line 468, in select

2023-11-07 15:31:56,305 - kivy - WARNING - stderr:     fd_event_list = self._selector.poll(timeout, max_ev)

2023-11-07 15:31:56,305 - kivy - WARNING - stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:31:56,305 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:31:59,411 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7fcd1c366200>" was accessed, it will be removed in a future version

2023-11-07 15:32:00,946 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2023-11-07 15:32:00,947 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2023-11-07 15:32:02,790 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-07 15:33:35,110 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f23a346a190>" was accessed, it will be removed in a future version

2023-11-07 15:33:35,732 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2023-11-07 15:33:35,733 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2023-11-07 15:33:38,477 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-07 15:34:05,904 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7effe9656190>" was accessed, it will be removed in a future version

2023-11-07 15:34:07,066 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2023-11-07 15:34:07,066 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2023-11-07 15:34:09,281 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-07 15:45:08,121 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7fdce94122e0>" was accessed, it will be removed in a future version

2023-11-07 15:45:09,021 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2023-11-07 15:45:09,021 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2023-11-07 15:45:11,506 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-07 15:45:50,613 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:45:50,613 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 430, in _handle_exception

2023-11-07 15:45:50,613 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg, exception_type=exception_type)

2023-11-07 15:45:50,613 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-07 15:45:50,614 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-07 15:45:50,614 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-07 15:45:50,614 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-07 15:45:50,614 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,614 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-07 15:45:50,614 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-07 15:45:50,614 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:45:50,614 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:45:50,614 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:45:50,762 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:45:50,762 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 430, in _handle_exception

2023-11-07 15:45:50,762 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg, exception_type=exception_type)

2023-11-07 15:45:50,762 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-07 15:45:50,762 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-07 15:45:50,763 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-07 15:45:50,763 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-07 15:45:50,763 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,763 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-07 15:45:50,763 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-07 15:45:50,763 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:45:50,763 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:45:50,763 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:45:50,764 - kivy - WARNING - stderr: Process Process-1:

2023-11-07 15:45:50,766 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:45:50,767 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap

2023-11-07 15:45:50,767 - kivy - WARNING - stderr:     self.run()

2023-11-07 15:45:50,767 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run

2023-11-07 15:45:50,767 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-07 15:45:50,767 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 406, in start

2023-11-07 15:45:50,767 - kivy - WARNING - stderr:     self._setup_interrupts()

2023-11-07 15:45:50,768 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 400, in _setup_interrupts

2023-11-07 15:45:50,768 - kivy - WARNING - stderr:     self._scheduler.run()

2023-11-07 15:45:50,768 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/sched.py", line 149, in run

2023-11-07 15:45:50,768 - kivy - WARNING - stderr:     delayfunc(time - now)

2023-11-07 15:45:50,768 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:45:50,768 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:45:50,768 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:45:50,904 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:45:50,905 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run

2023-11-07 15:45:50,905 - kivy - WARNING - stderr:     return runner.run(main)

2023-11-07 15:45:50,905 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,906 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run

2023-11-07 15:45:50,906 - kivy - WARNING - stderr:     return self._loop.run_until_complete(task)

2023-11-07 15:45:50,906 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,906 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-07 15:45:50,907 - kivy - WARNING - stderr:     self.run_forever()

2023-11-07 15:45:50,907 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-07 15:45:50,907 - kivy - WARNING - stderr:     self._run_once()

2023-11-07 15:45:50,908 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once

2023-11-07 15:45:50,908 - kivy - WARNING - stderr:     handle._run()

2023-11-07 15:45:50,909 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run

2023-11-07 15:45:50,909 - kivy - WARNING - stderr:     self._context.run(self._callback, *self._args)

2023-11-07 15:45:50,909 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 320, in mainCoro

2023-11-07 15:45:50,910 - kivy - WARNING - stderr:     await app.async_run()

2023-11-07 15:45:50,910 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/app.py", line 968, in async_run

2023-11-07 15:45:50,911 - kivy - WARNING - stderr:     await async_runTouchApp(async_lib=async_lib)

2023-11-07 15:45:50,911 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 597, in async_runTouchApp

2023-11-07 15:45:50,911 - kivy - WARNING - stderr:     await EventLoop.async_mainloop()

2023-11-07 15:45:50,912 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 354, in async_mainloop

2023-11-07 15:45:50,912 - kivy - WARNING - stderr:     await self.async_idle()

2023-11-07 15:45:50,912 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 422, in async_idle

2023-11-07 15:45:50,912 - kivy - WARNING - stderr:     self.dispatch_input()

2023-11-07 15:45:50,912 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 334, in dispatch_input

2023-11-07 15:45:50,912 - kivy - WARNING - stderr:     post_dispatch_input(*pop(0))

2023-11-07 15:45:50,912 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 302, in post_dispatch_input

2023-11-07 15:45:50,913 - kivy - WARNING - stderr:     wid.dispatch('on_touch_up', me)

2023-11-07 15:45:50,913 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch

2023-11-07 15:45:50,913 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up

2023-11-07 15:45:50,913 - kivy - WARNING - stderr:     self.dispatch('on_release')

2023-11-07 15:45:50,913 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch

2023-11-07 15:45:50,913 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch

2023-11-07 15:45:50,914 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1191, in kivy._event.EventObservers._dispatch

2023-11-07 15:45:50,914 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/lang/builder.py", line 55, in custom_callback

2023-11-07 15:45:50,914 - kivy - WARNING - stderr:     exec(__kvlang__.co_value, idmap)

2023-11-07 15:45:50,914 - kivy - WARNING - stderr:   File "<string>", line 42, in <module>

2023-11-07 15:45:50,914 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 217, in open_settings

2023-11-07 15:45:50,914 - kivy - WARNING - stderr:     return super().open_settings(*args)

2023-11-07 15:45:50,914 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,915 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/app.py", line 1084, in open_settings

2023-11-07 15:45:50,915 - kivy - WARNING - stderr:     self._app_settings = self.create_settings()

2023-11-07 15:45:50,915 - kivy - WARNING - stderr:                          ^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,915 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 204, in trace_dispatch

2023-11-07 15:45:50,924 - kivy - WARNING - stderr:     return thread_trace_func(frame, event, arg)

2023-11-07 15:45:50,924 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,924 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 440, in __call__

2023-11-07 15:45:50,925 - kivy - WARNING - stderr:     ).trace_dispatch(frame, event, arg)

2023-11-07 15:45:50,925 - kivy - WARNING - stderr:       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,925 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 988, in trace_dispatch

2023-11-07 15:45:50,925 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg)

2023-11-07 15:45:50,925 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-07 15:45:50,925 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-07 15:45:50,925 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-07 15:45:50,926 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-07 15:45:50,926 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,926 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-07 15:45:50,926 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-07 15:45:50,926 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:45:50,926 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:45:50,926 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:45:50,926 - kivy - WARNING - stderr: 

2023-11-07 15:45:50,926 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-07 15:45:50,927 - kivy - WARNING - stderr: 

2023-11-07 15:45:50,927 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:45:50,927 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main

2023-11-07 15:45:50,927 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-07 15:45:50,927 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,927 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 88, in _run_code

2023-11-07 15:45:50,927 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-07 15:45:50,927 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>

2023-11-07 15:45:50,927 - kivy - WARNING - stderr:     cli.main()

2023-11-07 15:45:50,927 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main

2023-11-07 15:45:50,927 - kivy - WARNING - stderr:     run()

2023-11-07 15:45:50,927 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module

2023-11-07 15:45:50,927 - kivy - WARNING - stderr:     run_module_as_main(options.target, alter_argv=True)

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 322, in <module>

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:     asyncio.run(mainCoro())

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 187, in run

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:     with Runner(debug=debug) as runner:

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 63, in __exit__

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:     self.close()

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 73, in close

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:     loop.run_until_complete(loop.shutdown_default_executor())

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:     self.run_forever()

2023-11-07 15:45:50,928 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-07 15:45:50,929 - kivy - WARNING - stderr:     self._run_once()

2023-11-07 15:45:50,929 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1873, in _run_once

2023-11-07 15:45:50,929 - kivy - WARNING - stderr:     event_list = self._selector.select(timeout)

2023-11-07 15:45:50,929 - kivy - WARNING - stderr:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,929 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/selectors.py", line 468, in select

2023-11-07 15:45:50,929 - kivy - WARNING - stderr:     fd_event_list = self._selector.poll(timeout, max_ev)

2023-11-07 15:45:50,929 - kivy - WARNING - stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:50,929 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:45:51,061 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>

2023-11-07 15:45:51,061 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:45:51,061 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1553, in _shutdown

2023-11-07 15:45:51,062 - kivy - WARNING - stderr: Exception in thread Thread-7 (_do_shutdown):

2023-11-07 15:45:51,063 - kivy - WARNING - stderr:     atexit_call()

2023-11-07 15:45:51,063 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:45:51,063 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit

2023-11-07 15:45:51,064 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 580, in _do_shutdown

2023-11-07 15:45:51,064 - kivy - WARNING - stderr:     t.join()

2023-11-07 15:45:51,064 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1112, in join

2023-11-07 15:45:51,065 - kivy - WARNING - stderr:     self._wait_for_tstate_lock()

2023-11-07 15:45:51,065 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock

2023-11-07 15:45:51,065 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_result, None)

2023-11-07 15:45:51,065 - kivy - WARNING - stderr:     if lock.acquire(block, timeout):

2023-11-07 15:45:51,066 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-07 15:45:51,066 - kivy - WARNING - stderr:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:45:51,066 - kivy - WARNING - stderr: KeyboardInterrupt: 

2023-11-07 15:45:51,068 - kivy - WARNING - stderr:     self._check_closed()

2023-11-07 15:45:51,069 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-07 15:45:51,080 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-07 15:45:51,086 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-07 15:45:51,091 - kivy - WARNING - stderr: 

2023-11-07 15:45:51,092 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-07 15:45:51,093 - kivy - WARNING - stderr: 

2023-11-07 15:45:51,093 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:45:51,093 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner

2023-11-07 15:45:51,094 - kivy - WARNING - stderr:     self.run()

2023-11-07 15:45:51,094 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 975, in run

2023-11-07 15:45:51,094 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-07 15:45:51,094 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 582, in _do_shutdown

2023-11-07 15:45:51,094 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_exception, ex)

2023-11-07 15:45:51,095 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-07 15:45:51,095 - kivy - WARNING - stderr:     self._check_closed()

2023-11-07 15:45:51,095 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-07 15:45:51,095 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-07 15:45:51,095 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-07 15:45:51,322 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:45:51,323 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2299, in __wait_for_threads_to_finish

2023-11-07 15:45:51,323 - kivy - WARNING - stderr:     time.sleep(1 / 10.)

2023-11-07 15:45:51,324 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:53:06,701 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f9678f62350>" was accessed, it will be removed in a future version

2023-11-07 15:53:08,188 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2023-11-07 15:53:08,188 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2023-11-07 15:53:10,074 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-07 15:54:01,029 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:54:01,029 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 430, in _handle_exception

2023-11-07 15:54:01,030 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg, exception_type=exception_type)

2023-11-07 15:54:01,030 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-07 15:54:01,030 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-07 15:54:01,030 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-07 15:54:01,030 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-07 15:54:01,030 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:01,030 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-07 15:54:01,030 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-07 15:54:01,030 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:54:01,030 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:54:01,030 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:54:02,647 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:54:02,647 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 430, in _handle_exception

2023-11-07 15:54:02,648 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg, exception_type=exception_type)

2023-11-07 15:54:02,648 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-07 15:54:02,648 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-07 15:54:02,648 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-07 15:54:02,648 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-07 15:54:02,648 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:02,648 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-07 15:54:02,648 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-07 15:54:02,648 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:54:02,648 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:54:02,648 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:54:02,650 - kivy - WARNING - stderr: Process Process-1:

2023-11-07 15:54:02,651 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:54:02,651 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap

2023-11-07 15:54:02,652 - kivy - WARNING - stderr:     self.run()

2023-11-07 15:54:02,652 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run

2023-11-07 15:54:02,652 - kivy - WARNING - stderr:     self._target(*self._args, **self._kwargs)

2023-11-07 15:54:02,652 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 406, in start

2023-11-07 15:54:02,652 - kivy - WARNING - stderr:     self._setup_interrupts()

2023-11-07 15:54:02,652 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/./rec_app/subs/driver/internal_bus.py", line 400, in _setup_interrupts

2023-11-07 15:54:02,652 - kivy - WARNING - stderr:     self._scheduler.run()

2023-11-07 15:54:02,652 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/sched.py", line 149, in run

2023-11-07 15:54:02,653 - kivy - WARNING - stderr:     delayfunc(time - now)

2023-11-07 15:54:02,653 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:54:02,653 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:54:02,653 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:54:02,826 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:54:02,826 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run

2023-11-07 15:54:02,826 - kivy - WARNING - stderr:     return runner.run(main)

2023-11-07 15:54:02,826 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^

2023-11-07 15:54:02,826 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run

2023-11-07 15:54:02,826 - kivy - WARNING - stderr:     return self._loop.run_until_complete(task)

2023-11-07 15:54:02,826 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:02,826 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-07 15:54:02,826 - kivy - WARNING - stderr:     self.run_forever()

2023-11-07 15:54:02,826 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-07 15:54:02,827 - kivy - WARNING - stderr:     self._run_once()

2023-11-07 15:54:02,827 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once

2023-11-07 15:54:02,827 - kivy - WARNING - stderr:     handle._run()

2023-11-07 15:54:02,827 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run

2023-11-07 15:54:02,827 - kivy - WARNING - stderr:     self._context.run(self._callback, *self._args)

2023-11-07 15:54:02,827 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 320, in mainCoro

2023-11-07 15:54:02,827 - kivy - WARNING - stderr:     await app.async_run()

2023-11-07 15:54:02,827 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/app.py", line 968, in async_run

2023-11-07 15:54:02,827 - kivy - WARNING - stderr:     await async_runTouchApp(async_lib=async_lib)

2023-11-07 15:54:02,827 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 597, in async_runTouchApp

2023-11-07 15:54:02,827 - kivy - WARNING - stderr:     await EventLoop.async_mainloop()

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 354, in async_mainloop

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:     await self.async_idle()

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 422, in async_idle

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:     self.dispatch_input()

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 334, in dispatch_input

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:     post_dispatch_input(*pop(0))

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/base.py", line 302, in post_dispatch_input

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:     wid.dispatch('on_touch_up', me)

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:     self.dispatch('on_release')

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "kivy/_event.pyx", line 1191, in kivy._event.EventObservers._dispatch

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/lang/builder.py", line 55, in custom_callback

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:     exec(__kvlang__.co_value, idmap)

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "<string>", line 42, in <module>

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 217, in open_settings

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:     return super().open_settings(*args)

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:02,828 - kivy - WARNING - stderr:   File "/home/dmitri/.cache/pypoetry/virtualenvs/mooseware-EfDc1YsZ-py3.11/lib/python3.11/site-packages/kivy/app.py", line 1084, in open_settings

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:     self._app_settings = self.create_settings()

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:                          ^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 204, in trace_dispatch

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:     return thread_trace_func(frame, event, arg)

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 440, in __call__

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:     ).trace_dispatch(frame, event, arg)

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 988, in trace_dispatch

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:     self.do_wait_suspend(thread, frame, event, arg)

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 165, in do_wait_suspend

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:     self._args[0].do_wait_suspend(*args, **kwargs)

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2070, in do_wait_suspend

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:     keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)

2023-11-07 15:54:02,829 - kivy - WARNING - stderr:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2106, in _do_wait_suspend

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:     time.sleep(0.01)

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 155, in _on_sigint

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:     raise KeyboardInterrupt()

2023-11-07 15:54:02,830 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:54:02,830 - kivy - WARNING - stderr: 

2023-11-07 15:54:02,830 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-07 15:54:02,830 - kivy - WARNING - stderr: 

2023-11-07 15:54:02,830 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 198, in _run_module_as_main

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/runpy.py", line 88, in _run_code

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:     cli.main()

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:     run()

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 317, in run_module

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:     run_module_as_main(options.target, alter_argv=True)

2023-11-07 15:54:02,830 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:     return _run_code(code, main_globals, None,

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:     exec(code, run_globals)

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:   File "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/rec_app/main.py", line 322, in <module>

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:     asyncio.run(mainCoro())

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 187, in run

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:     with Runner(debug=debug) as runner:

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 63, in __exit__

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:     self.close()

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/runners.py", line 73, in close

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:     loop.run_until_complete(loop.shutdown_default_executor())

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:     self.run_forever()

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 604, in run_forever

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:     self._run_once()

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 1873, in _run_once

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:     event_list = self._selector.select(timeout)

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:02,831 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/selectors.py", line 468, in select

2023-11-07 15:54:02,832 - kivy - WARNING - stderr:     fd_event_list = self._selector.poll(timeout, max_ev)

2023-11-07 15:54:02,832 - kivy - WARNING - stderr:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:02,832 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 15:54:03,835 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>

2023-11-07 15:54:03,835 - kivy - WARNING - stderr: Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>Exception in thread Thread-6 (_do_shutdown):

2023-11-07 15:54:03,836 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:54:03,836 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:54:03,836 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1553, in _shutdown

2023-11-07 15:54:03,837 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 580, in _do_shutdown

2023-11-07 15:54:03,838 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_result, None)

2023-11-07 15:54:03,838 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-07 15:54:03,838 - kivy - WARNING - stderr:     self._check_closed()

2023-11-07 15:54:03,838 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-07 15:54:03,839 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-07 15:54:03,839 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')    atexit_call()

2023-11-07 15:54:03,840 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-07 15:54:03,840 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit

2023-11-07 15:54:03,841 - kivy - WARNING - stderr: 

2023-11-07 15:54:03,842 - kivy - WARNING - stderr:     t.join()

2023-11-07 15:54:03,842 - kivy - WARNING - stderr: During handling of the above exception, another exception occurred:

2023-11-07 15:54:03,843 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1112, in join

2023-11-07 15:54:03,843 - kivy - WARNING - stderr: 

2023-11-07 15:54:03,843 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:54:03,844 - kivy - WARNING - stderr:     self._wait_for_tstate_lock()

2023-11-07 15:54:03,844 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner

2023-11-07 15:54:03,844 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock

2023-11-07 15:54:03,845 - kivy - WARNING - stderr:     self.run()

2023-11-07 15:54:03,845 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/threading.py", line 975, in run

2023-11-07 15:54:03,846 - kivy - WARNING - stderr:     if lock.acquire(block, timeout):

2023-11-07 15:54:03,846 - kivy - WARNING - stderr:     if lock.acquire(block, timeout):    self._target(*self._args, **self._kwargs)

2023-11-07 15:54:03,846 - kivy - WARNING - stderr:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2023-11-07 15:54:03,846 - kivy - WARNING - stderr: KeyboardInterrupt: 

2023-11-07 15:54:03,846 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 582, in _do_shutdown

2023-11-07 15:54:03,847 - kivy - WARNING - stderr:     self.call_soon_threadsafe(future.set_exception, ex)

2023-11-07 15:54:03,848 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 803, in call_soon_threadsafe

2023-11-07 15:54:03,848 - kivy - WARNING - stderr:     self._check_closed()

2023-11-07 15:54:03,848 - kivy - WARNING - stderr:   File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed

2023-11-07 15:54:03,848 - kivy - WARNING - stderr:     raise RuntimeError('Event loop is closed')

2023-11-07 15:54:03,848 - kivy - WARNING - stderr: RuntimeError: Event loop is closed

2023-11-07 15:54:04,013 - kivy - WARNING - stderr: Traceback (most recent call last):

2023-11-07 15:54:04,013 - kivy - WARNING - stderr:   File "/home/dmitri/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2299, in __wait_for_threads_to_finish

2023-11-07 15:54:04,013 - kivy - WARNING - stderr:     time.sleep(1 / 10.)

2023-11-07 15:54:04,014 - kivy - WARNING - stderr: KeyboardInterrupt

2023-11-07 21:54:46,014 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7fed6655e200>" was accessed, it will be removed in a future version

2023-11-07 21:54:47,253 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2023-11-07 21:54:47,253 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2023-11-07 21:54:47,257 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2023-11-07 21:54:47,257 - kivy - WARNING - Factory: Ignored class "SetTimeIn" re-declaration. Current -  module: None, cls: None, baseclass: TIn, filename: None. Ignored -  module: None, cls: None, baseclass: TIn, filename: None.

2023-11-07 21:54:47,257 - kivy - WARNING - Factory: Ignored class "SetIntMethod" re-declaration. Current -  module: None, cls: None, baseclass: DROPB, filename: None. Ignored -  module: None, cls: None, baseclass: DROPB, filename: None.

2023-11-07 21:54:47,257 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2023-11-07 21:54:49,389 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.

2023-11-07 22:51:06,643 - kivy - WARNING - Deprecated property "<BooleanProperty name=allow_stretch>" of object "<kivy.uix.image.Image object at 0x7f6b39c7a200>" was accessed, it will be removed in a future version

2023-11-07 22:51:07,286 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2023-11-07 22:51:07,286 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2023-11-07 22:51:07,289 - kivy - WARNING - Factory: Ignored class "Graph3" re-declaration. Current -  module: None, cls: None, baseclass: Graph, filename: None. Ignored -  module: None, cls: None, baseclass: Graph, filename: None.

2023-11-07 22:51:07,290 - kivy - WARNING - Factory: Ignored class "SetTimeIn" re-declaration. Current -  module: None, cls: None, baseclass: TIn, filename: None. Ignored -  module: None, cls: None, baseclass: TIn, filename: None.

2023-11-07 22:51:07,290 - kivy - WARNING - Factory: Ignored class "SetIntMethod" re-declaration. Current -  module: None, cls: None, baseclass: DROPB, filename: None. Ignored -  module: None, cls: None, baseclass: DROPB, filename: None.

2023-11-07 22:51:07,290 - kivy - WARNING - Factory: Ignored class "StimPanel" re-declaration. Current -  module: None, cls: <class 'subs.gui.misc.Stimulation.StimPanel'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: FloatLayout, filename: None.

2023-11-07 22:51:10,012 - kivy - WARNING - MTD: Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.
